name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (optional)'
        required: false
        type: string
env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: pnpm install

      - name: Set Git username
        run: |-
          git config --global user.name "Release It"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Publish default version
        if: ${{ inputs.version == '' }}
        run: pnpm release-it --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: ${{ inputs.version }}
        run: pnpm release-it --ci -i ${{ inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
