name: Automated tests
on: [push]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4.0.3
        with:
          cache: pnpm
          node-version: 20

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: |-
          pnpm eslint src "*.js" "*.ts"
          pnpm prettier --check src "*.js" "*.ts"

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests (Chrome)
        run: pnpm test -- --forbid-only

      - name: Run tests (Firefox)
        run: pnpm test -- --browser firefox

      - name: Run tests (WebKit)
        run: pnpm test -- --browser webkit
