name: Automated tests
on: [push]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4.1.5
      - uses: actions/setup-node@v4.0.2
        with:
          cache: yarn
          node-version: 20

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests (Chrome)
        run: yarn test --forbid-only

      - name: Run tests (Firefox)
        run: yarn test --browser firefox

      - name: Run tests (WebKit)
        run: yarn test --browser webkit
