name: Automated tests
on: [push]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      # - name: yarn install, test
      #   run: |
      #     yarn install
      #     yarn test
      # - name: yarn build
      #   run: yarn build
